
export const GET_TOKEN = 'GET_TOKEN';
export const GET_USER_DATA = 'GET_USER_DATA';
export const LOGIN = 'LOGIN';

export const SEARCH_ITEMS = 'SEARCH_ITEMS';
export const SEARCH_IS_LOADING = 'SEARCH_IS_LOADING';
export const SEARCH_UPDATE_RESULTS = 'SEARCH_UPDATE_RESULTS';

/*PLAYLIST*/
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const GET_USER_PLAYLISTS = 'GET_USER_PLAYLISTS';
export const CHOOSE_PLAYLIST = 'CHOOSE_PLAYLIST';
export const LOAD_TRACKS = 'LOAD_TRACKS';
export const UPDATE_TRACKS = 'ADD_TRACKS';
export const ADD_TRACKS_LOADING = 'ADD_TRACKS_LOADING';
export const ADD_TRACKS_ERROR = 'ADD_TRACKS_ERROR';
export const REMOVE_TRACK = 'REMOVE_TRACK';
export const REMOVE_TRACK_LOADING = 'REMOVE_TRACK_LOADING';
export const REMOVE_TRACK_ERROR = 'REMOVE_TRACK_ERROR';

